"""baseline schema

Revision ID: e4159bd5260f
Revises: 
Create Date: 2025-08-26 20:22:03.233870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4159bd5260f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('group_avatar', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('order_match_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'order_id', name='_user_order_uc')
    )
    op.create_table('orders',
    sa.Column('requested_rate_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cargo_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('to_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_locations_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('to_locations_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loading_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('routes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gps_monitoring', sa.Boolean(), nullable=True),
    sa.Column('truck_type', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('truck_quantity', sa.Integer(), nullable=True),
    sa.Column('load_date', sa.String(), nullable=True),
    sa.Column('unload_date', sa.String(), nullable=True),
    sa.Column('has_customs', sa.Boolean(), nullable=True),
    sa.Column('customs_info', sa.String(), nullable=True),
    sa.Column('adr', sa.Boolean(), nullable=True),
    sa.Column('adr_class', sa.String(), nullable=True),
    sa.Column('temp_mode', sa.Boolean(), nullable=True),
    sa.Column('temp_from', sa.String(), nullable=True),
    sa.Column('temp_to', sa.String(), nullable=True),
    sa.Column('rate_type', sa.String(), nullable=True),
    sa.Column('rate_with_vat', sa.String(), nullable=True),
    sa.Column('rate_no_vat', sa.String(), nullable=True),
    sa.Column('rate_cash', sa.String(), nullable=True),
    sa.Column('rate_currency', sa.String(), nullable=True),
    sa.Column('rate_to_card', sa.Boolean(), nullable=True),
    sa.Column('payment_scenario', sa.String(), nullable=True),
    sa.Column('payment_days', sa.String(), nullable=True),
    sa.Column('prepay_amount', sa.String(), nullable=True),
    sa.Column('postpay_days', sa.String(), nullable=True),
    sa.Column('payment_comment', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('transport_match_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.String(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transport_id', name='transport_match_views_user_transport_uc')
    )
    op.create_table('transports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('transport_kind', sa.String(), nullable=True),
    sa.Column('truck_type', sa.String(), nullable=True),
    sa.Column('body_length', sa.String(), nullable=True),
    sa.Column('body_width', sa.String(), nullable=True),
    sa.Column('body_height', sa.String(), nullable=True),
    sa.Column('trailer_length', sa.String(), nullable=True),
    sa.Column('trailer_width', sa.String(), nullable=True),
    sa.Column('trailer_height', sa.String(), nullable=True),
    sa.Column('load_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adr', sa.Boolean(), nullable=True),
    sa.Column('adr_class', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('gps_monitor', sa.Boolean(), nullable=True),
    sa.Column('special', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_location', sa.String(), nullable=True),
    sa.Column('from_radius', sa.String(), nullable=True),
    sa.Column('from_location_lat', sa.Float(), nullable=True),
    sa.Column('from_location_lng', sa.Float(), nullable=True),
    sa.Column('to_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_location_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ready_date_from', sa.String(), nullable=True),
    sa.Column('ready_date_to', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('regularity', sa.String(), nullable=True),
    sa.Column('rate_type', sa.String(), nullable=True),
    sa.Column('rate_with_vat', sa.String(), nullable=True),
    sa.Column('rate_without_vat', sa.String(), nullable=True),
    sa.Column('rate_cash', sa.String(), nullable=True),
    sa.Column('bargain', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('TRANSPORT', 'OWNER', 'MANAGER', 'EMPLOYEE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('docs_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('viber', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('person_type', sa.String(), nullable=True),
    sa.Column('fleet', sa.String(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('docs_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('final_rating', sa.Float(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('payload_before', sa.Text(), nullable=True),
    sa.Column('payload_after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_id'), 'admin_actions', ['id'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'accepted', 'rejected', 'viewed', name='bidstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_id'), 'bids', ['id'], unique=False)
    op.create_table('chat_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('file_type', sa.String(length=128), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_file_id'), 'chat_file', ['id'], unique=False)
    op.create_table('chat_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_participant_id'), 'chat_participant', ['id'], unique=False)
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_contact_request')
    )
    op.create_index(op.f('ix_contact_requests_id'), 'contact_requests', ['id'], unique=False)
    op.create_table('group_mute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='_user_chat_mute_uc')
    )
    op.create_index(op.f('ix_group_mute_chat_id'), 'group_mute', ['chat_id'], unique=False)
    op.create_index(op.f('ix_group_mute_user_id'), 'group_mute', ['user_id'], unique=False)
    op.create_table('internal_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_comments_manager_id'), 'internal_comments', ['manager_id'], unique=False)
    op.create_index(op.f('ix_internal_comments_order_id'), 'internal_comments', ['order_id'], unique=False)
    op.create_index(op.f('ix_internal_comments_transport_id'), 'internal_comments', ['transport_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'transport_id', 'user_id', name='_order_transport_user_uc')
    )
    op.create_index(op.f('ix_matches_order_id'), 'matches', ['order_id'], unique=False)
    op.create_index(op.f('ix_matches_transport_id'), 'matches', ['transport_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('matches_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transport_id', name='matches_viewed_user_transport_uc')
    )
    op.create_index(op.f('ix_matches_viewed_transport_id'), 'matches_viewed', ['transport_id'], unique=False)
    op.create_index(op.f('ix_matches_viewed_user_id'), 'matches_viewed', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ORDER', 'BID', 'CHAT', 'SYSTEM', 'ORDER_OVERDUE_1', 'ORDER_OVERDUE_4', 'ORDER_OVERDUE_7', 'ORDER_AUTO_DISABLED', 'TRANSPORT_OVERDUE_1', 'TRANSPORT_OVERDUE_4', 'TRANSPORT_OVERDUE_7', 'TRANSPORT_AUTO_DISABLED', 'TRANSPORT_REMOVED', 'ORDER_REMOVED', 'AUTO_MATCH', 'CONTACT_REQUEST', 'CONTACT_ACCEPTED', 'CONTACT_DECLINED', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('order_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('punctuality', sa.Integer(), nullable=False),
    sa.Column('communication', sa.Integer(), nullable=False),
    sa.Column('professionalism', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_table('saved_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'order_id', name='uq_saved_orders_user_order')
    )
    op.create_index(op.f('ix_saved_orders_order_id'), 'saved_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_saved_orders_user_id'), 'saved_orders', ['user_id'], unique=False)
    op.create_table('saved_transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transport_id', name='uq_saved_transports_user_transport')
    )
    op.create_index(op.f('ix_saved_transports_transport_id'), 'saved_transports', ['transport_id'], unique=False)
    op.create_index(op.f('ix_saved_transports_user_id'), 'saved_transports', ['user_id'], unique=False)
    op.create_table('tracking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_point_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_sessions_order_id'), 'tracking_sessions', ['order_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_share_token'), 'tracking_sessions', ['share_token'], unique=True)
    op.create_index(op.f('ix_tracking_sessions_transport_id'), 'tracking_sessions', ['transport_id'], unique=False)
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_user_block')
    )
    op.create_index(op.f('ix_user_blocks_blocked_id'), 'user_blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_user_blocks_blocker_id'), 'user_blocks', ['blocker_id'], unique=False)
    op.create_table('user_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_id', name='uq_user_contact')
    )
    op.create_index(op.f('ix_user_contacts_id'), 'user_contacts', ['id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=16), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['chat_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_table('tracking_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_points_session_id'), 'tracking_points', ['session_id'], unique=False)
    op.create_index(op.f('ix_tracking_points_ts'), 'tracking_points', ['ts'], unique=False)
    op.create_table('tracking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='trackingrequeststatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_requests_created_at'), 'tracking_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_requests_order_id'), 'tracking_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_tracking_requests_requester_user_id'), 'tracking_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_tracking_requests_status'), 'tracking_requests', ['status'], unique=False)
    op.create_index(op.f('ix_tracking_requests_target_user_id'), 'tracking_requests', ['target_user_id'], unique=False)
    op.create_table('tracking_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_share_links_id'), 'tracking_share_links', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_share_links_session_id'), 'tracking_share_links', ['session_id'], unique=False)
    op.create_index(op.f('ix_tracking_share_links_token'), 'tracking_share_links', ['token'], unique=True)
    op.create_table('tracking_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_shares_active'), 'tracking_shares', ['active'], unique=False)
    op.create_index(op.f('ix_tracking_shares_created_at'), 'tracking_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_shares_recipient_user_id'), 'tracking_shares', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_tracking_shares_session_id'), 'tracking_shares', ['session_id'], unique=False)
    op.create_table('chat_message_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_reaction_id'), 'chat_message_reaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_reaction_id'), table_name='chat_message_reaction')
    op.drop_table('chat_message_reaction')
    op.drop_index(op.f('ix_tracking_shares_session_id'), table_name='tracking_shares')
    op.drop_index(op.f('ix_tracking_shares_recipient_user_id'), table_name='tracking_shares')
    op.drop_index(op.f('ix_tracking_shares_created_at'), table_name='tracking_shares')
    op.drop_index(op.f('ix_tracking_shares_active'), table_name='tracking_shares')
    op.drop_table('tracking_shares')
    op.drop_index(op.f('ix_tracking_share_links_token'), table_name='tracking_share_links')
    op.drop_index(op.f('ix_tracking_share_links_session_id'), table_name='tracking_share_links')
    op.drop_index(op.f('ix_tracking_share_links_id'), table_name='tracking_share_links')
    op.drop_table('tracking_share_links')
    op.drop_index(op.f('ix_tracking_requests_target_user_id'), table_name='tracking_requests')
    op.drop_index(op.f('ix_tracking_requests_status'), table_name='tracking_requests')
    op.drop_index(op.f('ix_tracking_requests_requester_user_id'), table_name='tracking_requests')
    op.drop_index(op.f('ix_tracking_requests_order_id'), table_name='tracking_requests')
    op.drop_index(op.f('ix_tracking_requests_created_at'), table_name='tracking_requests')
    op.drop_table('tracking_requests')
    op.drop_index(op.f('ix_tracking_points_ts'), table_name='tracking_points')
    op.drop_index(op.f('ix_tracking_points_session_id'), table_name='tracking_points')
    op.drop_table('tracking_points')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_user_contacts_id'), table_name='user_contacts')
    op.drop_table('user_contacts')
    op.drop_index(op.f('ix_user_blocks_blocker_id'), table_name='user_blocks')
    op.drop_index(op.f('ix_user_blocks_blocked_id'), table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index(op.f('ix_tracking_sessions_transport_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_share_token'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_order_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_index(op.f('ix_saved_transports_user_id'), table_name='saved_transports')
    op.drop_index(op.f('ix_saved_transports_transport_id'), table_name='saved_transports')
    op.drop_table('saved_transports')
    op.drop_index(op.f('ix_saved_orders_user_id'), table_name='saved_orders')
    op.drop_index(op.f('ix_saved_orders_order_id'), table_name='saved_orders')
    op.drop_table('saved_orders')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_table('order_comments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_matches_viewed_user_id'), table_name='matches_viewed')
    op.drop_index(op.f('ix_matches_viewed_transport_id'), table_name='matches_viewed')
    op.drop_table('matches_viewed')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_transport_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_order_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_internal_comments_transport_id'), table_name='internal_comments')
    op.drop_index(op.f('ix_internal_comments_order_id'), table_name='internal_comments')
    op.drop_index(op.f('ix_internal_comments_manager_id'), table_name='internal_comments')
    op.drop_table('internal_comments')
    op.drop_index(op.f('ix_group_mute_user_id'), table_name='group_mute')
    op.drop_index(op.f('ix_group_mute_chat_id'), table_name='group_mute')
    op.drop_table('group_mute')
    op.drop_index(op.f('ix_contact_requests_id'), table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_index(op.f('ix_chat_participant_id'), table_name='chat_participant')
    op.drop_table('chat_participant')
    op.drop_index(op.f('ix_chat_file_id'), table_name='chat_file')
    op.drop_table('chat_file')
    op.drop_index(op.f('ix_bids_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_admin_actions_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('transports')
    op.drop_table('transport_match_views')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('order_match_views')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
