"""init

Revision ID: c1d693bcb4e8
Revises: 
Create Date: 2025-08-02 17:54:00.460494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d693bcb4e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.UUID(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transport_id', name='_user_transport_uc')
    )
    op.create_index(op.f('ix_matches_viewed_transport_id'), 'matches_viewed', ['transport_id'], unique=False)
    op.create_index(op.f('ix_matches_viewed_user_id'), 'matches_viewed', ['user_id'], unique=False)
    op.drop_table('blocked_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blocker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], name=op.f('blocked_users_blocked_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], name=op.f('blocked_users_blocker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blocked_users_pkey')),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name=op.f('_blocker_blocked_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_matches_viewed_user_id'), table_name='matches_viewed')
    op.drop_index(op.f('ix_matches_viewed_transport_id'), table_name='matches_viewed')
    op.drop_table('matches_viewed')
    # ### end Alembic commands ###
