"""Add matches table

Revision ID: 91e865a5e98d
Revises: c1d693bcb4e8
Create Date: 2025-08-03 21:17:54.149183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e865a5e98d'
down_revision: Union[str, Sequence[str], None] = 'c1d693bcb4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('_order_transport_user_uc', 'matches', ['order_id', 'transport_id', 'user_id'])
    op.create_index(op.f('ix_matches_order_id'), 'matches', ['order_id'], unique=False)
    op.create_index(op.f('ix_matches_transport_id'), 'matches', ['transport_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_transport_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_order_id'), table_name='matches')
    op.drop_constraint('_order_transport_user_uc', 'matches', type_='unique')
    op.alter_column('matches', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
